image:
  - Visual Studio 2017

environment:
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  matrix:
    - BUILD: MSVCDYNAMIC64
    - BUILD: MSVCSTATIC64
    - BUILD: MinGW32
    - BUILD: MinGW64
    - BUILD: Cygwin32
    - BUILD: Cygwin64

clone_depth: 5

build_script:
  - 'call "ci\build.bat"'

test_script:
  - 'call "ci\test.bat"'
