language: c

os:
  - linux
  - osx

env:
  - env: MODE=regular
  - env: MODE=disable-set
  - env: MODE=mini
  - env: MODE=minimalist
  - env: MODE=read-only

addons:
  apt:
    packages:
      - dpkg
      - gcc
      - libatm-dev
      - libperl-dev
      - libsensors4-dev
      - libssh2-1-dev
      - libssl-dev
      - make
      - perl-modules
      - pkg-config
      - python-dev
      - python-setuptools

sudo: required

before_script: ci/before.sh

script: ci/build.sh
