language: c

os:
  - linux
  - osx

# See also https://docs.travis-ci.com/user/reference/osx/
osx_image:
  - xcode12
  - xcode11.6
  - xcode11.5
  - xcode11.4
  - xcode11.3
  - xcode11.2
  - xcode11.1
  - xcode11
  - xcode10.3
  - xcode10.2
  - xcode10.1
  - xcode10
  - xcode9.4
  - xcode9.3
  - xcode9.2
  - xcode9.1
  - xcode9
  - xcode8.3
  - xcode8
  - xcode7.3

env:
  - MODE=regular
  - MODE=disable-set
  - MODE=mini
  - MODE=minimalist
  - MODE=read-only

addons:
  apt:
    packages:
      - dpkg
      - gcc
      - libatm-dev
      - libperl-dev
      - libsensors4-dev
      - libssh2-1-dev
      - libssl-dev
      - make
      - perl-modules
      - pkg-config
      - python-dev
      - python-setuptools
      - python3-dev
      - python3-setuptools

sudo: required

before_script: ci/before.sh

script: ci/build.sh
