language: c

os:
  - linux
  - osx

# Xcode 11.3.1 + OS/X 10.14. See also
# https://docs.travis-ci.com/user/reference/osx/
osx_image: xcode11.3

env:
  - MODE=regular
  - MODE=disable-set
  - MODE=mini
  - MODE=minimalist
  - MODE=read-only

addons:
  apt:
    packages:
      - dpkg
      - gcc
      - libatm-dev
      - libperl-dev
      - libsensors4-dev
      - libssh2-1-dev
      - libssl-dev
      - make
      - perl-modules
      - pkg-config
      - python-dev
      - python-setuptools
      - python3-dev
      - python3-setuptools

sudo: required

before_script: ci/before.sh

script: ci/build.sh
